"""
Django settings for ltv_updater project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file (for local development)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detect if we're running on Render
IS_RENDER = os.environ.get('RENDER') == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-099e&9k@*#s!*=_@u02!id83oe30(ie@bou!$p+9#e%s_*fb7u')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True' and not IS_RENDER

# Parse ALLOWED_HOSTS from environment variable (comma-separated)
_allowed_hosts_raw = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(',') if h.strip()] if _allowed_hosts_raw else []
if IS_RENDER:
    # On Render, add the service URL
    RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
    if RENDER_EXTERNAL_HOSTNAME:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
# In local dev, allow any host (e.g. Mac LAN IP when testing from a physical phone)
if DEBUG and '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('*')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'rest_framework.authtoken',
    'tickets',
]

# Add django-storages for S3 support in production
if os.environ.get('AWS_STORAGE_BUCKET_NAME'):
    INSTALLED_APPS.append('storages')

if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = ['127.0.0.1']

ROOT_URLCONF = 'ltv_updater.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tickets.context_processors.organization_context',
                'tickets.context_processors.feature_flags_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'ltv_updater.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL if provided (Render provides this), otherwise use SQLite for development
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Use app timezone so "today" and event filters match your business timezone (e.g. where events are held).
# Set TIME_ZONE in environment to override (e.g. America/New_York).
TIME_ZONE = os.environ.get('TIME_ZONE', 'America/Los_Angeles')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (uploaded CSVs, event flyers)
# Use S3 in production if configured, otherwise use local storage.
# If S3 returns Access Denied for media URLs, see docs/S3_MEDIA_SETUP.md.
if os.environ.get('AWS_STORAGE_BUCKET_NAME'):
    # AWS S3 settings
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN')
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    # None = do not set object ACL (required when bucket has "Block public access" for ACLs). Use bucket policy for public read.
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False
    
    # S3 Storage settings
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN or f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"}/'
    MEDIA_ROOT = ''
else:
    # Local media storage for development
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Google Docs API Configuration
GOOGLE_SERVICE_ACCOUNT_JSON = os.environ.get('GOOGLE_SERVICE_ACCOUNT_JSON', '')
GOOGLE_DOC_ID = os.environ.get('GOOGLE_DOC_ID', '')

# Google Maps API (Places Autocomplete on venue forms)
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')

# Chat Agent (LangChain + OpenAI)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_MODEL = os.environ.get('OPENAI_MODEL', 'gpt-4o')
CHAT_MAX_HISTORY = int(os.environ.get('CHAT_MAX_HISTORY', '50'))

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'
AUTHENTICATION_BACKENDS = [
    'tickets.backends.EmailBackend',
    'tickets.backends.PhoneBackend',
    'tickets.backends.EmailOTPBackend',
]

# Session settings — stay logged in for 30 days; OTP only required once per session
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60  # 30 days in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False   # persist across browser closes
SESSION_SAVE_EVERY_REQUEST = True         # refresh the 30-day window on each request

# Twilio (required in prod, optional in dev)
TWILIO_ACCOUNT_SID       = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN        = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_VERIFY_SERVICE_SID = os.environ.get('TWILIO_VERIFY_SERVICE_SID', '')
E2E_TEST_MODE = os.environ.get('E2E_TEST_MODE', 'False') == 'True'

# Absolute URL for building links in emails (survey invitations, etc.)
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# Stripe payment integration
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY      = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET  = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_CONNECTED_ACCOUNT_WEBHOOK_SECRET = os.environ.get('STRIPE_CONNECTED_ACCOUNT_WEBHOOK_SECRET', '')
STRIPE_CURRENCY        = os.environ.get('STRIPE_CURRENCY', 'usd')
STRIPE_TERMINAL_LOCATION_ID = os.environ.get('STRIPE_TERMINAL_LOCATION_ID', '')
APPLE_PAY_DOMAIN_ASSOCIATION = os.environ.get('APPLE_PAY_DOMAIN_ASSOCIATION', '')

# Apple Tap to Pay on iPhone — opaque version string for Apple's T&Cs.
# Bump (via env var) when Apple publishes new terms to force merchants
# through Setup re-acceptance on next app open.
TAP_TO_PAY_TERMS_VERSION = os.environ.get('TAP_TO_PAY_TERMS_VERSION', '2026-03-01')

# ISO-3166 alpha-2 country codes where Apple supports Tap to Pay on iPhone.
# Source: https://developer.apple.com/tap-to-pay/regions/ (last reviewed 2026-05).
TAP_TO_PAY_SUPPORTED_COUNTRIES = {
    c.strip().upper()
    for c in os.environ.get(
        'TAP_TO_PAY_SUPPORTED_COUNTRIES',
        'US,GB,AU,CA,FR,IT,NL,JP,BR,DE,CZ,AT,CH,DK,FI,NO,SE,IE,ES,PT,BE,PL,UA,TW,HK,SG',
    ).split(',')
    if c.strip()
}

# Seconds to cache the Stripe Connect account lookup behind /merchant/status/.
# The iOS app may poll on every foreground transition — caching keeps the
# Stripe API call cheap without making the splash trigger feel laggy.
TAP_TO_PAY_STATUS_CACHE_TTL = int(os.environ.get('TAP_TO_PAY_STATUS_CACHE_TTL', '60'))

# App Store reviewer bypass for the phone-OTP flow. Phones in this dict skip
# Twilio Verify entirely and accept the mapped fixed OTP code. Use the NANP
# fictional range (+1 555-01xx) so the numbers can never reach a real person.
# Document the active phone + OTP in App Store Connect review notes.
APP_REVIEW_TEST_PHONES = {
    '+15555550100': '424242',
}

# Meta Ads integration
FACEBOOK_APP_ID = os.environ.get('FACEBOOK_APP_ID', '')
FACEBOOK_APP_SECRET = os.environ.get('FACEBOOK_APP_SECRET', '')
FACEBOOK_GRAPH_API_VERSION = os.environ.get('FACEBOOK_GRAPH_API_VERSION', 'v21.0')

# Mailchimp integration
MAILCHIMP_CLIENT_ID = os.environ.get('MAILCHIMP_CLIENT_ID', '')
MAILCHIMP_CLIENT_SECRET = os.environ.get('MAILCHIMP_CLIENT_SECRET', '')

# Email backend configuration — SendGrid SMTP for all environments
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@cueup.co')

# Custom error views
CSRF_FAILURE_VIEW = 'tickets.views.csrf_failure'

# Trust the SSL-terminating proxy in all envs (Render in prod, ngrok in dev) so
# request.is_secure() / build_absolute_uri() produce https:// URLs for Stripe.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Security settings for production
if IS_RENDER or not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Explicitly list trusted origins so mobile browsers (which always send the
    # Origin header) are not rejected by the CSRF middleware due to a scheme
    # mismatch when Django infers http:// behind the proxy.
    _csrf_origins = []
    if RENDER_EXTERNAL_HOSTNAME:
        _csrf_origins.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')
    _extra = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    if _extra:
        _csrf_origins.extend([o.strip() for o in _extra.split(',') if o.strip()])
    if _csrf_origins:
        CSRF_TRUSTED_ORIGINS = _csrf_origins

# Celery configuration
_CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL')
CELERY_BROKER_URL = _CELERY_BROKER_URL or 'redis://localhost:6379/0'
# When no broker URL is set (e.g. local dev without Redis), run tasks eagerly and do not use Redis backend
CELERY_TASK_ALWAYS_EAGER = not _CELERY_BROKER_URL
CELERY_TASK_EAGER_PROPAGATES = True
if _CELERY_BROKER_URL:
    CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', _CELERY_BROKER_URL)
else:
    # Use cache backend so Celery never connects to Redis when broker is unset (Celery may treat None as "use broker")
    CELERY_RESULT_BACKEND = 'cache+memory://'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# Bound Redis client count so Celery can't exhaust Render Redis (~50 client cap).
# Combined with the cache pool below (4 workers × max_connections=5 = 20),
# this caps total Redis clients at roughly 35.
CELERY_BROKER_POOL_LIMIT = 10
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'max_connections': 10,
    'socket_keepalive': True,
}
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
    'max_connections': 5,
    'socket_keepalive': True,
}

# Cache framework — Redis when available, in-memory fallback for dev
if _CELERY_BROKER_URL:
    # Use DB 1 to isolate from Celery broker on DB 0.
    # urlparse handles Render's connectionString format (no DB suffix) correctly:
    #   redis://red-xxx.render.com:6379   → redis://red-xxx.render.com:6379/1
    #   redis://red-xxx.render.com:6379/0 → redis://red-xxx.render.com:6379/1
    from urllib.parse import urlparse, urlunparse
    _parsed = urlparse(_CELERY_BROKER_URL)
    _cache_url = urlunparse(_parsed._replace(path='/1'))
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _cache_url,
            'TIMEOUT': 300,
            'OPTIONS': {
                'socket_connect_timeout': 0.5,
                'socket_timeout': 0.5,
                'socket_keepalive': True,
                'health_check_interval': 30,
                'max_connections': 5,  # 4 Gunicorn workers × 5 = 20 connections, leaves headroom for Celery
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'TIMEOUT': 300,
        }
    }

# Sentry — error tracking + performance monitoring
# Set SENTRY_DSN in Render environment variables to enable.
_SENTRY_DSN = os.environ.get('SENTRY_DSN')
if _SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=_SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        environment='production' if IS_RENDER else 'development',
        # Capture 100% of transactions for performance monitoring.
        # Lower to 0.2 (20%) if volume gets large and costs become a concern.
        traces_sample_rate=1.0,
        # Profile 100% of sessions that have an active transaction (CPU flamegraphs).
        profile_session_sample_rate=1.0,
        profile_lifecycle="trace",
        # Don't send PII (user emails/IPs) unless you explicitly want it.
        send_default_pii=False,
    )

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
