# Generated by Django 5.2.4 on 2026-01-05 02:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvformat',
            name='uses_tiers',
            field=models.BooleanField(default=False, help_text='If True, this format uses tier-based pricing with allotments. Only applicable when requires_manual_pricing is True.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tier_name',
            field=models.CharField(blank=True, help_text='Denormalized tier name for display/querying', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(help_text="Tier name (e.g., 'Early Bird', 'Regular')", max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allotment', models.IntegerField(help_text='Maximum number of tickets available in this tier')),
                ('order', models.IntegerField(help_text='Priority/order (1 = first tier, 2 = second, etc.)')),
                ('tickets_assigned', models.IntegerField(default=0, help_text='Number of tickets already assigned to this tier')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='tickets.uploadedfile')),
            ],
            options={
                'ordering': ['ticket_type', 'order'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Assigned pricing tier (if tier-based pricing is used)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.tickettier'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tier'], name='tickets_tic_tier_id_b46dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettier',
            index=models.Index(fields=['ticket_type', 'order'], name='tickets_tic_ticket__b7e49b_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettier',
            index=models.Index(fields=['uploaded_file'], name='tickets_tic_uploade_a8fedf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettier',
            unique_together={('uploaded_file', 'ticket_type', 'order')},
        ),
    ]
