# Generated by Django 5.2.4 on 2026-01-05 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_csvformat_uses_tiers_ticket_tier_name_tickettier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('city', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['name', 'city'],
                'indexes': [models.Index(fields=['name', 'city'], name='tickets_ven_name_e420f3_idx')],
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_new', to='tickets.venue'),
        ),
    ]
