# Generated by Django 5.2.4 on 2026-01-05 21:21

from django.db import migrations


def migrate_venue_data(apps, schema_editor):
    """Convert existing venue strings to Venue objects."""
    Event = apps.get_model('tickets', 'Event')
    Venue = apps.get_model('tickets', 'Venue')
    
    # Get all events and migrate venue strings to Venue objects
    for event in Event.objects.all():
        venue_string = event.venue  # This is the old CharField
        
        if venue_string:
            # Try to parse venue string (e.g., "Seattle, WA" or "The Fillmore, San Francisco")
            if ',' in venue_string:
                parts = [p.strip() for p in venue_string.rsplit(',', 1)]
                if len(parts) == 2:
                    venue_name = parts[0]
                    venue_city = parts[1]
                else:
                    venue_name = venue_string
                    venue_city = 'Unknown'
            else:
                venue_name = venue_string
                venue_city = 'Unknown'
            
            # Get or create venue
            venue, created = Venue.objects.get_or_create(
                name=venue_name,
                city=venue_city,
                defaults={'name': venue_name, 'city': venue_city}
            )
            
            # Assign to event
            event.venue_new = venue
            event.save(update_fields=['venue_new'])
        else:
            # Create default venue for empty strings
            default_venue, created = Venue.objects.get_or_create(
                name='Unknown Venue',
                city='Unknown',
                defaults={'name': 'Unknown Venue', 'city': 'Unknown'}
            )
            event.venue_new = default_venue
            event.save(update_fields=['venue_new'])


def reverse_migrate_venue_data(apps, schema_editor):
    """Reverse migration - not applicable since we can't convert back to CharField easily."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_add_venue_model'),
    ]

    operations = [
        migrations.RunPython(migrate_venue_data, reverse_migrate_venue_data),
    ]
