# Generated by Django 5.2.4 on 2026-01-05 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_migrate_venue_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue_new',
            new_name='venue',
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='tickets.venue'),
        ),
    ]
