# Generated by Django 5.2.4 on 2026-01-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_finalize_venue_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Total ticket capacity for the event (optional)', null=True),
        ),
    ]
