# Generated by Django 5.2.4 on 2026-02-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_add_venue_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Total capacity for the venue (optional)', null=True),
        ),
    ]
