# Generated by Django 5.2.4 on 2026-02-14 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_add_venue_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parking_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='EventTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_lineup', to='tickets.event')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
