# Generated by Django 5.2.4 on 2026-02-14 16:38

from django.db import migrations, models

VALID_PARKING_KEYS = ('', 'street', 'lot', 'none', 'venue')


def clear_invalid_parking_info(apps, schema_editor):
    """Set parking_info to empty for any value not in PARKING_CHOICES keys."""
    Event = apps.get_model('tickets', 'Event')
    Event.objects.exclude(parking_info__in=VALID_PARKING_KEYS).update(parking_info='')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_add_event_ticket_parking_and_event_talent'),
    ]

    operations = [
        migrations.RunPython(clear_invalid_parking_info, noop),
        migrations.AlterField(
            model_name='event',
            name='parking_info',
            field=models.CharField(blank=True, choices=[('', '—'), ('street', 'Street parking'), ('lot', 'Lot available'), ('none', 'No parking'), ('venue', 'See venue / contact venue')], max_length=50),
        ),
    ]
