# Generated by Django 5.2.4 on 2026-02-14 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_parking_info_dropdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('dropdown', 'Dropdown')], default='dropdown', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tickets.customfield')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='EventCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.customfield')),
                ('custom_field_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.customfieldoption')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='tickets.event')),
            ],
            options={
                'unique_together': {('event', 'custom_field')},
            },
        ),
    ]
