# Generated by Django 5.2.4 on 2026-02-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_organization_required_remove_customfield_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('organization', 'name', 'city')},
        ),
    ]
