# Generated by Django 5.2.4 on 2026-02-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_venue_unique_together_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('organization', 'name', 'start_date')},
        ),
    ]
