# Generated by Django 5.2.4 on 2026-02-14 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_seed_default_org_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='default_option',
            field=models.ForeignKey(blank=True, help_text='Option to pre-select when creating a new event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_custom_fields', to='tickets.customfieldoption'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='required',
            field=models.BooleanField(default=False, help_text='When set, event form requires a value for this field.'),
        ),
    ]
