# Generated by Django 5.2.4 on 2026-02-14 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_parking_info_to_custom_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_orders', to='tickets.event'),
        ),
    ]
