# Generated by Django 5.2.4 on 2026-02-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_ticketorder_event_cascade_for_event_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rfm_frequency_score',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='rfm_monetary_score',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='rfm_recency_score',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='rfm_segment',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='rfm_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
