# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_add_customer_rfm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='rfm_recalc_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
