# Generated by Django 5.2.4 on 2026-02-15 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_seed_accepting_vendors_custom_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticketorder',
            name='tickets_tic_order_n_d35cbb_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', '-start_date'], name='tickets_eve_organiz_e86cba_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_order'], name='tickets_tic_ticket__dc4259_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['event', 'total_amount'], name='tickets_tic_event_i_b326a8_idx'),
        ),
    ]
