# Generated by Django 5.2.4 on 2026-02-15 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_remove_ticketorder_tickets_tic_order_n_d35cbb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('talent', 'Talent / Artist Fees'), ('venue', 'Venue Rental'), ('production', 'Production / AV / Sound'), ('marketing', 'Marketing / Promotion'), ('staffing', 'Staffing / Security'), ('catering', 'Catering / Hospitality'), ('insurance', 'Insurance / Permits'), ('travel', 'Travel / Accommodation'), ('other', 'Other')], db_index=True, max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tickets.event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['event', 'category'], name='tickets_eve_event_i_95fd06_idx'), models.Index(fields=['event', '-expense_date'], name='tickets_eve_event_i_87ee55_idx')],
            },
        ),
    ]
