# Generated by Django 5.2.4 on 2026-02-16 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_eventexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to='tickets.organization')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventIncome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_income', to='tickets.event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('income_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_income_lines', to='tickets.incomesource')),
            ],
            options={
                'ordering': ['income_source__order', 'income_source__name'],
            },
        ),
        migrations.AddIndex(
            model_name='incomesource',
            index=models.Index(fields=['organization', 'order'], name='tickets_inc_organiz_3a129e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incomesource',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='eventincome',
            index=models.Index(fields=['event', 'income_source'], name='tickets_eve_event_i_e2267b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventincome',
            index=models.Index(fields=['event', '-income_date'], name='tickets_eve_event_i_b577bf_idx'),
        ),
    ]
