# Generated by Django 5.2.4 on 2026-02-17 01:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(help_text='Denormalized from customer at send time', max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_invitations', to='tickets.customer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_invitations', to='tickets.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_invitations', to='tickets.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('star_rating', 'Star Rating (1-5)'), ('nps', 'NPS Score (0-10)'), ('text', 'Free Text')], max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(blank=True, help_text='Null = not event-specific (org default or system default)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='tickets.event')),
                ('organization', models.ForeignKey(blank=True, help_text='Null = system default question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='tickets.organization')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='tickets.customer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='tickets.event')),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='tickets.surveyinvitation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='tickets.organization')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('star_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 star rating', null=True)),
                ('nps_score', models.PositiveSmallIntegerField(blank=True, help_text='0-10 NPS score', null=True)),
                ('text_answer', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tickets.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tickets.surveyresponse')),
            ],
            options={
                'ordering': ['question__position'],
            },
        ),
        migrations.AddIndex(
            model_name='surveyinvitation',
            index=models.Index(fields=['event', 'sent_at'], name='tickets_sur_event_i_5c5602_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyinvitation',
            unique_together={('event', 'customer')},
        ),
        migrations.AddIndex(
            model_name='surveyquestion',
            index=models.Index(fields=['event', 'position'], name='tickets_sur_event_i_99e7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyquestion',
            index=models.Index(fields=['organization', 'position'], name='tickets_sur_organiz_93c8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['event', '-submitted_at'], name='tickets_sur_event_i_563387_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyanswer',
            unique_together={('response', 'question')},
        ),
    ]
