# Generated by Django 5.2.4 on 2026-02-17 01:57

from django.db import migrations


def seed_default_questions(apps, schema_editor):
    SurveyQuestion = apps.get_model('tickets', 'SurveyQuestion')
    defaults = [
        {
            'question_text': 'How would you rate your overall experience?',
            'question_type': 'star_rating',
            'position': 1,
            'is_required': True,
            'is_active': True,
        },
        {
            'question_text': 'How likely are you to recommend this event to a friend or colleague?',
            'question_type': 'nps',
            'position': 2,
            'is_required': True,
            'is_active': True,
        },
        {
            'question_text': 'What did you enjoy most about the event?',
            'question_type': 'text',
            'position': 3,
            'is_required': False,
            'is_active': True,
        },
        {
            'question_text': 'What could we improve for future events?',
            'question_type': 'text',
            'position': 4,
            'is_required': False,
            'is_active': True,
        },
    ]
    for q in defaults:
        SurveyQuestion.objects.create(event=None, organization=None, **q)


def remove_default_questions(apps, schema_editor):
    SurveyQuestion = apps.get_model('tickets', 'SurveyQuestion')
    SurveyQuestion.objects.filter(event__isnull=True, organization__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_surveyinvitation_surveyquestion_surveyresponse_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_default_questions, remove_default_questions),
    ]
