# Generated by Django 5.2.4 on 2026-02-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_add_organization_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID after sync (create-only).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(choices=[('America/Los_Angeles', 'Pacific'), ('America/Denver', 'Mountain'), ('America/Chicago', 'Central'), ('America/New_York', 'Eastern'), ('America/Anchorage', 'Alaska'), ('Pacific/Honolulu', 'Hawaii')], default='America/Los_Angeles', help_text='Timezone where the event takes place', max_length=50),
        ),
    ]
