# Generated by Django 5.2.4 on 2026-02-18 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_add_event_timezone_and_google_calendar_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipedreamCalendarConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_url', models.URLField(max_length=500)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipedream_calendar_connection', to='tickets.organization')),
            ],
            options={
                'verbose_name': 'Pipedream calendar connection',
                'verbose_name_plural': 'Pipedream calendar connections',
            },
        ),
    ]
