# Generated by Django 5.2.4 on 2026-02-19 02:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_add_pipedream_calendar_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleableTicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Buyer-facing name, e.g. 'General Admission'", max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='USD price; 0.00 = free', max_digits=10)),
                ('quantity_limit', models.PositiveIntegerField(blank=True, help_text='Max tickets available; null = unlimited', null=True)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Hidden from public page when False')),
                ('sale_start', models.DateTimeField(blank=True, null=True)),
                ('sale_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order on public page')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleable_ticket_types', to='tickets.event')),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['event', 'is_active'], name='tickets_sal_event_i_f145d9_idx'), models.Index(fields=['event', 'order'], name='tickets_sal_event_i_26ad80_idx')],
            },
        ),
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('line_items_snapshot', models.JSONField(default=list)),
                ('amount_total_cents', models.PositiveIntegerField(default=0)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_checkout_sessions', to='tickets.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_checkout_sessions', to='tickets.organization')),
                ('ticket_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_checkout_session', to='tickets.ticketorder')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='tickets_str_organiz_e07e43_idx'), models.Index(fields=['event', 'status'], name='tickets_str_event_i_18da35_idx')],
            },
        ),
    ]
