# Generated by Django 5.2.4 on 2026-02-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_saleabletickettype_stripecheckoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticketing_type',
            field=models.CharField(choices=[('direct', 'Direct (sell tickets on this platform)'), ('external', 'External (upload CSV ticket data)')], default='external', max_length=20),
        ),
    ]
