# Generated by Django 5.2.4 on 2026-02-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0042_event_ticketing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='event_flyers/'),
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
