# Generated by Django 5.2.4 on 2026-02-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0043_event_flyer_event_summary_alter_venue_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_buy_page_views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the public ticket page (/buy/<id>/) was loaded.'),
        ),
    ]
