# Generated by Django 5.2.4 on 2026-02-20 20:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0044_add_event_public_buy_page_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvitation',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('attendee', 'Attendee'), ('both', 'Organizer & Attendee')], default='organizer', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('attendee', 'Attendee'), ('both', 'Organizer & Attendee')], db_index=True, default='organizer', max_length=20),
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('signup_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', '-created_at'], name='tickets_pho_phone_n_55bcd8_idx')],
            },
        ),
    ]
