# Generated by Django 5.2.4 on 2026-02-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0045_organizationinvitation_role_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
