# Generated by Django 5.2.4 on 2026-02-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0048_finance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='platform_fee_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
