# Generated by Django 5.2.4 on 2026-02-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0051_ticketorder_refunded_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='tickets_eve_ticketi_a4aa12_idx',
            old_name='tickets_eve_ticketi_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Publication state; only meaningful for direct ticketing events.', max_length=20),
        ),
        migrations.AlterField(
            model_name='stripecheckoutsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
