# Generated by Django 5.2.4 on 2026-02-26 19:59

from django.db import migrations, models


def set_existing_organizers_to_admin(apps, schema_editor):
    UserProfile = apps.get_model('tickets', 'UserProfile')
    UserProfile.objects.filter(
        role__in=['organizer', 'both'],
        organization__isnull=False,
    ).update(org_role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_event_status_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvitation',
            name='org_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('host', 'Host'), ('doorman', 'Doorman')], default='host', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('host', 'Host'), ('doorman', 'Doorman')], db_index=True, max_length=20, null=True),
        ),
        migrations.RunPython(set_existing_organizers_to_admin, migrations.RunPython.noop),
    ]
