# Generated by Django 5.2.4 on 2026-03-06 04:44

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0055_stripecheckoutsession_discount_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='display_order_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, null=True, storage=tickets.models._get_media_storage, upload_to='event_flyers/'),
        ),
        migrations.CreateModel(
            name='OrderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_counter', to='tickets.organization')),
            ],
        ),
    ]
