# Generated by Django 5.2.4 on 2026-03-06 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0058_ticketorder_external_order_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='is_in_person',
            field=models.BooleanField(db_index=True, default=False, help_text='Order was processed in person (no customer identity).'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['event', 'is_in_person'], name='tickets_tic_event_i_4593ad_idx'),
        ),
    ]
