# Generated by Django 5.2.4 on 2026-03-06 18:51

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0060_backfill_is_in_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, null=True, storage=tickets.models._get_media_storage, upload_to=tickets.models._event_flyer_upload_to),
        ),
    ]
