# Generated by Django 5.2.4 on 2026-03-07 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0064_ticketorder_checked_in_at_ticketorder_checked_in_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSurveyUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('error_log', models.TextField(blank=True, help_text='JSON list of per-row parse errors')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_survey_uploads', to='tickets.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalSurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(db_index=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('overall_rating', models.CharField(blank=True, db_index=True, max_length=30)),
                ('nps_score', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('enjoyed', models.JSONField(default=list)),
                ('genres', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('crowd_vibe', models.CharField(blank=True, max_length=80)),
                ('venue_feel', models.CharField(blank=True, max_length=80)),
                ('pre_event_info', models.CharField(blank=True, max_length=80)),
                ('found_out_how', models.CharField(blank=True, max_length=200)),
                ('text_feedback', models.TextField(blank=True)),
                ('raffle_email', models.EmailField(blank=True, max_length=254)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_survey_responses', to='tickets.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_survey_responses', to='tickets.organization')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tickets.externalsurveyupload')),
            ],
            options={
                'ordering': ['-responded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='externalsurveyupload',
            index=models.Index(fields=['organization', '-uploaded_at'], name='tickets_ext_organiz_76d4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsurveyresponse',
            index=models.Index(fields=['organization', '-responded_at'], name='tickets_ext_organiz_068c59_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsurveyresponse',
            index=models.Index(fields=['organization', 'city'], name='tickets_ext_organiz_53c97e_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsurveyresponse',
            index=models.Index(fields=['organization', 'nps_score'], name='tickets_ext_organiz_e0c3a2_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsurveyresponse',
            index=models.Index(fields=['upload', 'city'], name='tickets_ext_upload__352fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsurveyresponse',
            index=models.Index(fields=['event', '-responded_at'], name='tickets_ext_event_i_3eae7d_idx'),
        ),
    ]
