# Generated by Django 5.2.4 on 2026-03-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0065_externalsurveyupload_externalsurveyresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, default='', help_text='Facebook Pixel ID for conversion tracking on the public ticketing flow.', max_length=20),
        ),
    ]
