# Generated by Django 5.2.4 on 2026-03-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0066_add_facebook_pixel_id_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='meta_capi_access_token',
            field=models.CharField(blank=True, default='', help_text='Meta Conversions API access token for server-side event reporting.', max_length=255),
        ),
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='fb_browser_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores _fbp, _fbc, client IP, user agent for CAPI Purchase call on webhook.'),
        ),
    ]
