# Generated by Django 5.2.4 on 2026-03-11 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0067_add_capi_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleableTicketTypeTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allotment', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='tickets.saleabletickettype')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['ticket_type', 'order'], name='tickets_sal_ticket__c10539_idx')],
                'unique_together': {('ticket_type', 'order')},
            },
        ),
    ]
