# Generated by Django 5.2.4 on 2026-03-11 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0068_saleabletickettypetier'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleabletickettype',
            name='unlocks_after',
            field=models.ForeignKey(blank=True, help_text='This ticket type will be shown but disabled until the selected ticket type sells out.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_by', to='tickets.saleabletickettype'),
        ),
    ]
