# Generated by Django 5.2.4 on 2026-03-14 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0071_organization_waitlist_feature_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerWaitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organizer Waitlist Entry',
                'verbose_name_plural': 'Organizer Waitlist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='waitlistentry',
            new_name='tickets_wai_ticket__4387b6_idx',
            old_name='tickets_wai_ticket__idx',
        ),
        migrations.RenameIndex(
            model_name='waitlistentry',
            new_name='tickets_wai_hold_to_c110aa_idx',
            old_name='tickets_wai_hold_to_idx',
        ),
        migrations.AddField(
            model_name='organizerwaitlist',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
