# Generated by Django 5.2.4 on 2026-03-15 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0072_organizerwaitlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scanner_pin',
            field=models.CharField(blank=True, db_index=True, help_text='6-digit PIN for guest scanner access (no Cue account required).', max_length=8, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ScannerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_sessions', to='tickets.event')),
            ],
            options={
                'indexes': [models.Index(fields=['token', 'is_active'], name='tickets_sca_token_bebd5a_idx')],
            },
        ),
    ]
