# Generated by Django 5.2.4 on 2026-03-25 23:15

import django.db.models.deletion
import tickets.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0077_add_checkout_hotpath_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Label to identify this key, e.g. 'Instagram DM Agent'", max_length=100)),
                ('key', models.CharField(db_index=True, default=tickets.models._generate_api_key, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organization API key',
                'verbose_name_plural': 'Organization API keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='ticketorder',
            new_name='tickets_tic_custome_4de869_idx',
            old_name='tickets_tic_custome_refund_idx',
        ),
        migrations.RenameIndex(
            model_name='waitlistentry',
            new_name='tickets_wai_ticket__0eadbf_idx',
            old_name='tickets_wai_tt_email_exp_pur_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='public_buy_page_views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the public ticket page (/e/<id>/) was loaded.'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, help_text='Stripe Transfer ID (tr_xxx) - set after successful call.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organizationapikey',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tickets.organization'),
        ),
        migrations.AddIndex(
            model_name='organizationapikey',
            index=models.Index(fields=['key', 'is_active'], name='tickets_org_key_97838f_idx'),
        ),
    ]
