# Generated by Django 5.2.4 on 2026-04-01 16:58

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0078_add_organization_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='csv_file',
            field=models.FileField(blank=True, null=True, storage=tickets.models._get_media_storage, upload_to=tickets.models._csv_upload_to),
        ),
    ]
