# Generated by Django 5.2.4 on 2026-04-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0079_add_csv_file_to_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='available_on',
            field=models.DateTimeField(blank=True, help_text='When this payment settles into the Stripe platform balance (from balance_transaction.available_on).', null=True),
        ),
        migrations.AddIndex(
            model_name='stripecheckoutsession',
            index=models.Index(fields=['organization', 'status', 'available_on'], name='tickets_str_organiz_a473ae_idx'),
        ),
    ]
