# Generated by Django 5.2.4 on 2026-04-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0080_add_available_on_to_stripecheckoutsession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
    ]
