# Generated by Django 5.2.4 on 2026-04-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0081_remove_event_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
