# Generated by Django 5.2.4 on 2026-04-04 01:45

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0082_trackinglink_stripecheckoutsession_tracking_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=tickets.models._get_media_storage, upload_to='org_photos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
