# Generated by Django 5.2.4 on 2026-04-08 02:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.db.models import Sum
from django.db.models.functions import Coalesce


def backfill_computed_total_revenue(apps, schema_editor):
    """Populate computed_total_revenue for all existing events."""
    Event = apps.get_model('tickets', 'Event')
    TicketOrder = apps.get_model('tickets', 'TicketOrder')
    EventIncome = apps.get_model('tickets', 'EventIncome')
    for event in Event.objects.all():
        order_total = TicketOrder.objects.filter(event=event).aggregate(
            t=Coalesce(Sum('total_amount'), Decimal('0.00'))
        )['t']
        income_total = EventIncome.objects.filter(
            event=event, deleted_at__isnull=True
        ).aggregate(
            t=Coalesce(Sum('amount'), Decimal('0.00'))
        )['t']
        event.computed_total_revenue = order_total + income_total
        event.save(update_fields=['computed_total_revenue'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0085_userprofile_terms_accepted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='computed_total_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Denormalized sum of ticket revenue + additional income; maintained by signals.', max_digits=12),
        ),
        migrations.RunPython(backfill_computed_total_revenue, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_order', 'price'], name='tkt_ticketorder_price_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['event', 'refunded_at'], name='tktorder_event_refund_idx'),
        ),
    ]
