# Generated by Django 5.2.4 on 2026-04-08 22:38

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0086_event_list_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cached_paid_ticket_count',
            field=models.IntegerField(default=0, help_text='Denormalized count of non-refunded paid tickets; maintained by signals and CSV import.'),
        ),
        migrations.AddField(
            model_name='event',
            name='cached_paid_ticket_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Denormalized sum of non-refunded paid ticket prices; maintained by signals and CSV import.', max_digits=12),
        ),
        migrations.AddField(
            model_name='event',
            name='cached_ticket_count',
            field=models.IntegerField(default=0, help_text='Denormalized total ticket count; maintained by signals and CSV import.'),
        ),
        migrations.AddIndex(
            model_name='eventexpense',
            index=models.Index(fields=['event', 'deleted_at'], name='tickets_eve_event_i_9489f2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventincome',
            index=models.Index(fields=['event', 'deleted_at'], name='tickets_eve_event_i_1d78f1_idx'),
        ),
    ]
