# Generated by Django 5.2.4 on 2026-04-09 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0088_backfill_event_cached_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['event', 'uploaded_file'], name='tktorder_event_upload_idx'),
        ),
    ]
