# Generated by Django 5.2.4 on 2026-04-09 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0089_ticketorder_upload_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['event', 'order_date'], name='tktorder_event_orderdate_idx'),
        ),
    ]
