# Generated by Django 5.2.4 on 2026-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0090_event_detail_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='stripe_payout_id',
            field=models.CharField(blank=True, help_text='Stripe Payout ID (po_xxx) - set via payout.created webhook on the connected account.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, help_text='Stripe Transfer ID (tr_xxx) - set after successful Transfer call.', max_length=255, null=True, unique=True),
        ),
    ]
