# Generated by Django 5.2.4 on 2026-04-12 03:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0092_featureflagsettings'),
    ]

    operations = [
        # Drop leftover M2M table from a previous partial migration attempt
        migrations.RunSQL(
            "DROP TABLE IF EXISTS tickets_customer_tags;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_opt_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False, help_text='True after Stripe confirms details_submitted, charges_enabled, and payouts_enabled.'),
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange')], default='blue', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tags', to='tickets.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='customers', to='tickets.customertag'),
        ),
    ]
