# Generated by Django 5.2.4 on 2026-04-16 03:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0099_saleabletickettype_max_per_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDailyPageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_page_views', to='tickets.event')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['event', 'date'], name='tickets_eve_event_i_acda3e_idx')],
                'unique_together': {('event', 'date')},
            },
        ),
    ]
