# Generated by Django 5.2.4 on 2026-04-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0101_event_social_proof_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='show_attendee_count',
            field=models.BooleanField(default=True, help_text="Show the exact number of others (e.g. '+ 5 others'). When off, shows '+ others' without a count."),
        ),
    ]
