# Generated by Django 5.2.4 on 2026-04-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0103_customer_email_unique_per_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='sms_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
