# Generated by Django 5.2.4 on 2026-05-07 03:41

import django.db.models.deletion
import tickets.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0103_customer_email_unique_per_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(db_index=True, default=tickets.models._generate_client_id, max_length=100, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('redirect_uris', models.JSONField(default=list, help_text='Allowed redirect URIs — exact match enforced.')),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'OAuth client',
                'verbose_name_plural': 'OAuth clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, default=tickets.models._generate_auth_code, max_length=100, unique=True)),
                ('code_challenge', models.CharField(max_length=200)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_auth_codes', to='tickets.organization')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='tickets.oauthclient')),
            ],
            options={
                'verbose_name': 'OAuth authorization code',
                'verbose_name_plural': 'OAuth authorization codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'used'], name='tickets_oau_code_7ea23e_idx')],
            },
        ),
        migrations.CreateModel(
            name='OAuthAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, default=tickets.models._generate_access_token, max_length=200, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_access_tokens', to='tickets.organization')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='tickets.oauthclient')),
            ],
            options={
                'verbose_name': 'OAuth access token',
                'verbose_name_plural': 'OAuth access tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'expires_at'], name='tickets_oau_token_8fb3de_idx')],
            },
        ),
    ]
