# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0105_oauth_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='meta_ads_access_token',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='organization',
            name='meta_ads_account_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='meta_ads_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='meta_ads_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='meta_ads_user_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='eventexpense',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eventexpense',
            name='external_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eventexpense',
            name='source',
            field=models.CharField(
                choices=[('manual', 'Manual'), ('meta_ads', 'Meta Ads')],
                db_index=True,
                default='manual',
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name='eventexpense',
            constraint=models.UniqueConstraint(
                condition=models.Q(source='meta_ads', deleted_at__isnull=True),
                fields=('event',),
                name='uniq_active_meta_expense_per_event',
            ),
        ),
    ]
