# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0106_meta_ads_integration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventexpense',
            name='uniq_active_meta_expense_per_event',
        ),
        migrations.AddConstraint(
            model_name='eventexpense',
            constraint=models.UniqueConstraint(
                condition=models.Q(source='meta_ads', deleted_at__isnull=True),
                fields=('event', 'source', 'external_id'),
                name='uniq_active_meta_expense_per_campaign',
            ),
        ),
    ]
