# Generated by Django 5.2.4 on 2026-05-08

import django.db.models.deletion
import uuid
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0107_meta_ads_multiple_campaigns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mailchimp_access_token',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='organization',
            name='mailchimp_account_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='mailchimp_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='mailchimp_dc',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='mailchimp_login_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='EventEmailCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('source', models.CharField(choices=[('mailchimp', 'Mailchimp')], db_index=True, default='mailchimp', max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('campaign_title', models.CharField(max_length=300)),
                ('subject_line', models.CharField(blank=True, default='', max_length=500)),
                ('send_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_url', models.URLField(blank=True, default='', max_length=500)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('opens', models.PositiveIntegerField(default=0)),
                ('unique_opens', models.PositiveIntegerField(default=0)),
                ('open_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('click_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('bounces', models.PositiveIntegerField(default=0)),
                ('unsubscribes', models.PositiveIntegerField(default=0)),
                ('abuse_reports', models.PositiveIntegerField(default=0)),
                ('ecommerce_orders', models.PositiveIntegerField(default=0)),
                ('ecommerce_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('match_confidence', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4)),
                ('match_reasoning', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('external_metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='tickets.event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-send_time', '-created_at'],
                'indexes': [
                    models.Index(fields=['event', 'source'], name='tickets_eve_event_i_121478_idx'),
                    models.Index(fields=['source', 'external_id'], name='tickets_eve_source_da5b00_idx'),
                    models.Index(fields=['event', 'deleted_at'], name='tickets_eve_event_i_7f1276_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(source='mailchimp', deleted_at__isnull=True),
                        fields=('event', 'source', 'external_id'),
                        name='uniq_active_email_campaign',
                    ),
                ],
            },
        ),
    ]
