# Generated by Django 5.2.4 on 2026-05-10

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0108_mailchimp_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='mailchimp_access_token',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mailchimp_account_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mailchimp_account_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mailchimp_dc',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mailchimp_login_email',
        ),
        migrations.CreateModel(
            name='PipedreamConnectedAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('app_slug', models.CharField(db_index=True, max_length=100)),
                ('external_user_id', models.CharField(db_index=True, max_length=255)),
                ('account_id', models.CharField(db_index=True, max_length=100)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('healthy', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('external_metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipedream_connected_accounts', to='tickets.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['app_slug', '-connected_at', '-created_at'],
                'indexes': [
                    models.Index(fields=['organization', 'app_slug'], name='tickets_pip_organiz_c07b9a_idx'),
                    models.Index(fields=['external_user_id', 'app_slug'], name='tickets_pip_externa_b5c8b9_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(deleted_at__isnull=True),
                        fields=('organization', 'app_slug'),
                        name='uniq_active_pipedream_account',
                    ),
                ],
            },
        ),
    ]
