# Generated by Django 5.2.4 on 2026-05-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0109_mailchimp_pipedream_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mailchimp_access_token',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='organization',
            name='mailchimp_account_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='mailchimp_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='mailchimp_dc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='mailchimp_login_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.DeleteModel(
            name='PipedreamConnectedAccount',
        ),
    ]
