# Generated by Django 5.2.4 on 2026-05-11 19:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0110_organization_mailchimp_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('sales_pacing', 'Sales pacing'), ('post_event_wrapup', 'Post-event wrap-up'), ('winback_audience', 'Win-back audience'), ('marketing_attribution', 'Marketing attribution')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], db_index=True, default='new', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20)),
                ('confidence', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('evidence_json', models.JSONField(blank=True, default=dict)),
                ('recommended_action_json', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(max_length=160)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='tickets.customer')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='tickets.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='tickets.organization')),
            ],
            options={
                'ordering': ['status', 'priority', '-confidence', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', 'priority'], name='tickets_air_organiz_51bbbc_idx'), models.Index(fields=['organization', 'kind', 'status'], name='tickets_air_organiz_8254e1_idx'), models.Index(fields=['event', 'status'], name='tickets_air_event_i_afb143_idx'), models.Index(fields=['customer', 'status'], name='tickets_air_custome_5587f3_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'dedupe_key'), name='ai_recommendation_org_dedupe_unique')],
            },
        ),
    ]
