# Generated by Codex on 2026-05-11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0112_remove_event_ai_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITokenUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(choices=[('chat_agent', 'Chat agent'), ('meta_campaign_match', 'Meta campaign match'), ('mailchimp_campaign_match', 'Mailchimp campaign match')], db_index=True, max_length=50)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('occurred_at', models.DateTimeField(db_index=True, default=timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_token_usage', to='tickets.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_token_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI token usage',
                'verbose_name_plural': 'AI token usage',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [
                    models.Index(fields=['organization', 'occurred_at'], name='aiusage_org_time_idx'),
                    models.Index(fields=['organization', 'feature', 'occurred_at'], name='aiusage_org_feature_idx'),
                    models.Index(fields=['organization', 'model_name', 'occurred_at'], name='aiusage_org_model_idx'),
                ],
            },
        ),
    ]
