# Generated by Django 5.2.4 on 2026-05-13 18:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0113_ai_token_usage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slicktext_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='slicktext_brand_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='slicktext_brand_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='slicktext_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='feature',
            field=models.CharField(choices=[('chat_agent', 'Chat agent'), ('meta_campaign_match', 'Meta campaign match'), ('mailchimp_campaign_match', 'Mailchimp campaign match'), ('slicktext_campaign_match', 'SlickText campaign match')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='EventSMSCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('source', models.CharField(choices=[('slicktext', 'SlickText')], db_index=True, default='slicktext', max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('message', models.CharField(blank=True, default='', max_length=1600)),
                ('media_url', models.URLField(blank=True, default='', max_length=500)),
                ('send_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('audience_size', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('click_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('unsubscribes', models.PositiveIntegerField(default=0)),
                ('unsubscribe_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('match_confidence', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4)),
                ('match_reasoning', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('external_metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_campaigns', to='tickets.event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-send_time', '-created_at'],
                'indexes': [models.Index(fields=['event', 'source'], name='tickets_eve_event_i_2af7e3_idx'), models.Index(fields=['source', 'external_id'], name='tickets_eve_source_5a59cd_idx'), models.Index(fields=['event', 'deleted_at'], name='tickets_eve_event_i_aa3e37_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('source', 'slicktext')), fields=('event', 'source', 'external_id'), name='uniq_active_sms_campaign')],
            },
        ),
    ]
