# Generated by Django 5.2.4 on 2026-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0114_organization_slicktext_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitokenusage',
            name='feature',
            field=models.CharField(choices=[('chat_agent', 'Chat agent'), ('meta_campaign_match', 'Meta campaign match'), ('mailchimp_campaign_match', 'Mailchimp campaign match'), ('slicktext_campaign_match', 'SlickText campaign match'), ('marketing_narrative', 'Marketing narrative')], db_index=True, max_length=50),
        ),
    ]
