# Generated by Django 5.2.4 on 2026-05-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0116_campaign_review_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventemailcampaign',
            name='manual_emails_sent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventemailcampaign',
            name='manual_unique_opens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventemailcampaign',
            name='manual_unsubscribes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsmscampaign',
            name='manual_audience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsmscampaign',
            name='manual_unsubscribes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
