# Generated by Django 5.2.4 on 2026-05-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0117_campaign_extra_manual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvitation',
            name='invited_via',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
