# Generated by Django 5.2.4 on 2026-05-20 04:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0118_organizationinvitation_invited_via_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('channel', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_sends', to='tickets.organization')),
                ('ticket_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_sends', to='tickets.ticketorder')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', '-created_at'], name='tickets_rec_organiz_3c781f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TapToPayTermsAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=64)),
                ('accepted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tap_to_pay_acceptances', to='tickets.organization')),
                ('scanner_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tap_to_pay_acceptances', to='tickets.scannersession')),
            ],
            options={
                'verbose_name': 'Tap to Pay Terms Acceptance',
                'verbose_name_plural': 'Tap to Pay Terms Acceptances',
                'indexes': [models.Index(fields=['organization', '-accepted_at'], name='tickets_tap_organiz_d0f331_idx')],
            },
        ),
    ]
