# Generated by Django 5.2.4 on 2026-05-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0119_receiptsend_taptopaytermsacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_terminal_location_id',
            field=models.CharField(blank=True, default='', help_text="Stripe Terminal Location ID (tml_xxx) scoped to this merchant's Connect account. Created lazily on first in-person sale and cached forever — Locations don't expire and aren't per-sale.", max_length=64),
        ),
    ]
