# Generated by Django 5.2.4 on 2026-05-20 18:54

import django.db.models.deletion
import tickets.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0120_organization_stripe_terminal_location_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeformFormSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('form_id', models.CharField(max_length=64)),
                ('form_title', models.CharField(max_length=255)),
                ('webhook_id', models.CharField(blank=True, default='', max_length=64)),
                ('webhook_secret', models.CharField(default=tickets.models._generate_typeform_webhook_secret, max_length=64)),
                ('field_map', models.JSONField(default=dict, help_text='Map of Typeform field ref/id → ExternalSurveyResponse field name.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Typeform form subscription',
                'verbose_name_plural': 'Typeform form subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='externalsurveyresponse',
            name='match_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='externalsurveyresponse',
            name='match_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='externalsurveyresponse',
            name='suggested_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_survey_responses', to='tickets.event'),
        ),
        migrations.AddField(
            model_name='externalsurveyresponse',
            name='typeform_response_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='typeform_access_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='typeform_account_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='typeform_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='feature',
            field=models.CharField(choices=[('chat_agent', 'Chat agent'), ('meta_campaign_match', 'Meta campaign match'), ('mailchimp_campaign_match', 'Mailchimp campaign match'), ('slicktext_campaign_match', 'SlickText campaign match'), ('marketing_narrative', 'Marketing narrative'), ('typeform_event_match', 'Typeform event match')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='externalsurveyresponse',
            index=models.Index(fields=['organization', 'typeform_response_id'], name='tickets_ext_organiz_36b94c_idx'),
        ),
        migrations.AddField(
            model_name='typeformformsubscription',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeformformsubscription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeform_subscriptions', to='tickets.organization'),
        ),
        migrations.AddField(
            model_name='typeformformsubscription',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeformformsubscription',
            name='upload',
            field=models.ForeignKey(blank=True, help_text='Synthetic upload row so the existing surveys UI groups responses by form.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeform_subscriptions', to='tickets.externalsurveyupload'),
        ),
        migrations.AddIndex(
            model_name='typeformformsubscription',
            index=models.Index(fields=['organization', 'is_active'], name='tickets_typ_organiz_6be3e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typeformformsubscription',
            unique_together={('organization', 'form_id')},
        ),
    ]
