# Generated by Django 5.2.4 on 2026-05-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0121_typeform_integration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeformformsubscription',
            name='field_map',
        ),
        migrations.AddField(
            model_name='externalsurveyresponse',
            name='raw_answers',
            field=models.JSONField(blank=True, default=list, help_text='Full list of {id, ref, type, title, value} dicts from Typeform.'),
        ),
    ]
