# Generated by Django 5.2.4 on 2026-05-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0122_typeform_raw_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsurveyresponse',
            name='answers_mapped_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the LLM answer mapper has populated structured columns from raw_answers.', null=True),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='feature',
            field=models.CharField(choices=[('chat_agent', 'Chat agent'), ('meta_campaign_match', 'Meta campaign match'), ('mailchimp_campaign_match', 'Mailchimp campaign match'), ('slicktext_campaign_match', 'SlickText campaign match'), ('marketing_narrative', 'Marketing narrative'), ('typeform_event_match', 'Typeform event match'), ('typeform_answer_map', 'Typeform answer mapping')], db_index=True, max_length=50),
        ),
    ]
