# Generated by Django 5.2.4 on 2026-05-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0123_typeform_answers_mapped_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalsurveyresponse',
            name='answers_mapped_at',
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='feature',
            field=models.CharField(choices=[('chat_agent', 'Chat agent'), ('meta_campaign_match', 'Meta campaign match'), ('mailchimp_campaign_match', 'Mailchimp campaign match'), ('slicktext_campaign_match', 'SlickText campaign match'), ('marketing_narrative', 'Marketing narrative'), ('typeform_event_match', 'Typeform event match')], db_index=True, max_length=50),
        ),
    ]
