# Generated by Django 5.2.4 on 2026-05-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0124_remove_typeform_answer_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeformformsubscription',
            name='field_map',
            field=models.JSONField(blank=True, default=dict, help_text='Map of Typeform field ref/id → ExternalSurveyResponse column name (e.g. {"q1_ref": "overall_rating", "email_id": "email"}). Empty = only raw_answers populated; no structured columns set.'),
        ),
    ]
