# Generated by Django 5.2.4 on 2026-05-22 14:17

from django.db import migrations, models


def empty_dicts_to_null(apps, schema_editor):
    """Existing field_map={} rows can't be distinguished from never-saved subscriptions.
    Treat them as fresh — the next visit will auto-prefill and the user re-saves.
    """
    Sub = apps.get_model('tickets', 'TypeformFormSubscription')
    Sub.objects.filter(field_map={}).update(field_map=None)


def null_to_empty_dicts(apps, schema_editor):
    """Reverse: restore the prior default."""
    Sub = apps.get_model('tickets', 'TypeformFormSubscription')
    Sub.objects.filter(field_map__isnull=True).update(field_map={})


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0125_typeform_field_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeformformsubscription',
            name='field_map',
            field=models.JSONField(blank=True, default=None, help_text='Map of Typeform field ref/id → ExternalSurveyResponse column name (e.g. {"q1_ref": "overall_rating", "email_id": "email"}). null = never saved through the editor (auto-suggest on first visit); {} = saved with everything explicitly Ignored; {...} = saved with at least one mapped field.', null=True),
        ),
        migrations.RunPython(empty_dicts_to_null, reverse_code=null_to_empty_dicts),
    ]
