# Generated by Django 5.2.4 on 2026-05-22 15:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0125_typeform_field_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative dollars refunded (partial + full). Equals total_amount when fully refunded.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stripecheckoutsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
