# Generated by Django 5.2.4 on 2026-05-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0126_typeform_field_map_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeformformsubscription',
            name='questions',
            field=models.JSONField(blank=True, default=list, help_text="Cached snapshot of the form's leaf questions: [{id, ref, type, title, group_title}, ...]. Refreshed whenever we call TypeformClient.get_form() — used as the source of truth for question titles when rendering responses (raw_answers may have empty titles for older rows ingested before group-walking was fixed)."),
        ),
    ]
