# Generated by Django 5.2.4 on 2026-05-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0126_ticketorder_refunded_amount_and_more'),
        ('tickets', '0127_typeform_subscription_questions'),
    ]

    operations = [
    ]
