# Generated by Django 5.2.4 on 2026-05-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0128_merge_20260522_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecommendation',
            name='kind',
            field=models.CharField(choices=[('sales_pacing', 'Sales pacing'), ('post_event_wrapup', 'Post-event wrap-up'), ('winback_audience', 'Win-back audience'), ('marketing_attribution', 'Marketing attribution'), ('marketing_unconfirmed', 'Marketing match unconfirmed')], db_index=True, max_length=40),
        ),
    ]
