# Generated by Django 5.2.4 on 2026-05-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0128_merge_20260522_0933'),
        ('tickets', '0129_alter_airecommendation_kind'),
    ]

    operations = [
    ]
