# Generated by Django 5.2.4 on 2026-05-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0133_backfill_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe PaymentIntent ID for in-person/Tap-to-Pay sales. Used to attach Stripe-sent receipts.', max_length=255),
        ),
    ]
