# Generated by Django 5.2.4 on 2026-05-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0133_backfill_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mailchimp_campaign_title_hints',
            field=models.TextField(blank=True, default='', help_text="Optional guidance for the AI campaign matcher about your campaign naming conventions. Example: 'Campaigns prefixed lv- are for Las Vegas events. Format is lv-MMDDYYYY-email-NN where MMDDYYYY is the event date.'"),
        ),
    ]
