# Generated by Django 5.2.4 on 2026-06-03 02:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0135_ticket_type_description_rich_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sms_marketing_enabled',
            field=models.BooleanField(default=False, help_text='Gates the native marketing SMS feature for this org. Off by default; enable per-org for pilot rollout. FeatureFlagSettings is a global singleton and cannot scope to individual orgs, so the SMS gate lives here.'),
        ),
        migrations.CreateModel(
            name='SMSRecipientList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('filter_criteria', models.JSONField(blank=True, default=dict, help_text="e.g. {'rfm_segment': ['Champions'], 'tag_ids': [...], 'min_ltv': '100.00'}")),
                ('manual_include_ids', models.JSONField(blank=True, default=list)),
                ('manual_exclude_ids', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_recipient_lists', to='tickets.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=1600)),
                ('link_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('audience_size', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_sms_campaigns', to='tickets.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_campaigns', to='tickets.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('recipient_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='tickets.smsrecipientlist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneSuppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('reason', models.CharField(choices=[('twilio_stop', 'Twilio STOP'), ('manual', 'Manual'), ('bounce', 'Bounce')], default='twilio_stop', max_length=20)),
                ('organization', models.ForeignKey(blank=True, help_text='Null = global suppression (all orgs). Set = per-org unsubscribe.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_suppressions', to='tickets.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['phone', 'organization'], name='tickets_pho_phone_cd00f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('phone', 'organization'), name='uniq_phone_suppression_phone_org')],
            },
        ),
        migrations.CreateModel(
            name='SMSMessageRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('undelivered', 'Undelivered'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('twilio_sid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('error_code', models.CharField(blank=True, default='', max_length=20)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='tickets.smscampaign')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_message_recipients', to='tickets.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'status'], name='tickets_sms_campaig_3651bf_idx'), models.Index(fields=['twilio_sid'], name='tickets_sms_twilio__bd2eca_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='smsrecipientlist',
            index=models.Index(fields=['organization', '-created_at'], name='tickets_sms_organiz_595aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='smscampaign',
            index=models.Index(fields=['organization', '-created_at'], name='tickets_sms_organiz_bbb6f6_idx'),
        ),
        migrations.AddIndex(
            model_name='smscampaign',
            index=models.Index(fields=['organization', 'status'], name='tickets_sms_organiz_a492a4_idx'),
        ),
        migrations.AddIndex(
            model_name='smscampaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='tickets_sms_status_ca2cd8_idx'),
        ),
    ]
