# Generated by Django 5.2.4 on 2026-06-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0136_organization_sms_marketing_enabled_smsrecipientlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessagerecipient',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smsmessagerecipient',
            name='click_token',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='smsmessagerecipient',
            name='first_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsmessagerecipient',
            name='opted_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
