# Generated by Django 5.2.4 on 2026-06-03 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0137_smsmessagerecipient_click_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sms_credit_balance_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SMSCreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('topup', 'Top-up'), ('charge', 'Campaign charge'), ('refund', 'Refund'), ('adjustment', 'Manual adjustment')], db_index=True, max_length=12)),
                ('amount_cents', models.IntegerField(help_text='Signed: + credit, - debit.')),
                ('balance_after_cents', models.PositiveIntegerField()),
                ('stripe_checkout_session_id', models.CharField(blank=True, help_text='Set on TOPUP rows; unique so webhook retries cannot double-credit.', max_length=255, null=True, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='tickets.smscampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_credit_transactions', to='tickets.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='tickets_sms_organiz_cb5afa_idx')],
            },
        ),
    ]
