# Generated by Django 5.2.4 on 2026-06-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0139_smscampaign_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Platform billing Stripe Customer (cus_xxx) for charging the org. Distinct from stripe_account_id (Connect payouts).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_pm_brand',
            field=models.CharField(blank=True, help_text="Card brand, e.g. 'visa'.", max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_pm_exp_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_pm_exp_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_pm_id',
            field=models.CharField(blank=True, help_text='Saved Stripe PaymentMethod (pm_xxx) for one-click SMS top-ups.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_pm_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of the saved card.', max_length=4),
        ),
    ]
