# Generated by Django 5.2.4 on 2026-06-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0140_organization_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscampaign',
            name='recipient_list',
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='filter_criteria',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'rfm_segment': ['VIP'], 'tag_ids': [...], 'event_id': '...'}"),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='manual_exclude_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='manual_include_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='SMSRecipientList',
        ),
    ]
