# Generated by Django 5.2.4 on 2026-06-04 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0140_organization_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscampaign',
            name='tracking_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_campaigns', to='tickets.trackinglink'),
        ),
    ]
