# Generated by Django 5.2.4 on 2026-06-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0141_remove_smscampaign_recipient_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleabletickettype',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, help_text="Show an 'Only X left' warning once remaining tickets drop to this number or fewer. Leave blank to disable the warning.", null=True),
        ),
    ]
