# Generated by Django 5.2.4 on 2026-06-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0142_saleabletickettype_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventexpense',
            name='api_attributed_orders',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventexpense',
            name='api_attributed_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
