# Generated by Django 5.2.4 on 2026-06-07 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0142_saleabletickettype_low_stock_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_tier_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, help_text='Branding / intro copy describing the program to your team.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one program per organization can be active at a time.')),
                ('recalc_in_progress', models.BooleanField(default=False)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_programs', to='tickets.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('rank', models.PositiveIntegerField(default=0, help_text='Higher rank = better tier. Used to break ties when a customer qualifies for several tiers.')),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange')], default='blue', max_length=20)),
                ('perks', models.TextField(blank=True, help_text='Describe the rewards and perks members of this tier earn.')),
                ('min_lifetime_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum total spend (lifetime value) to qualify.', max_digits=10, null=True)),
                ('min_order_count', models.PositiveIntegerField(blank=True, help_text='Minimum number of orders placed to qualify.', null=True)),
                ('min_events_purchased', models.PositiveIntegerField(blank=True, help_text='Minimum number of distinct events purchased to qualify.', null=True)),
                ('min_tickets_purchased', models.PositiveIntegerField(blank=True, help_text='Minimum number of tickets purchased to qualify.', null=True)),
                ('max_days_since_last_order', models.PositiveIntegerField(blank=True, help_text='Must have ordered within this many days to qualify (recency).', null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='tickets.loyaltyprogram')),
            ],
            options={
                'ordering': ['-rank', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tickets.loyaltytier'),
        ),
        migrations.AddIndex(
            model_name='loyaltyprogram',
            index=models.Index(fields=['organization', 'is_active'], name='tickets_loy_organiz_547f1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyprogram',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('organization',), name='one_active_loyalty_program_per_org'),
        ),
        migrations.AddConstraint(
            model_name='loyaltytier',
            constraint=models.UniqueConstraint(fields=('program', 'name'), name='loyaltytier_program_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='loyaltytier',
            constraint=models.UniqueConstraint(fields=('program', 'rank'), name='loyaltytier_program_rank_unique'),
        ),
    ]
