# Generated by Django 5.2.4 on 2026-06-10 19:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0143_customer_loyalty_tier_updated_at_loyaltyprogram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lifetime_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='points_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='points_basis',
            field=models.CharField(choices=[('per_ticket', 'Per ticket'), ('per_dollar', 'Per dollar spent')], default='per_ticket', max_length=12),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='points_enabled',
            field=models.BooleanField(default=False, help_text='Award loyalty points for ticket purchases.'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='points_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text="Points per ticket (or per dollar). Note: with 'per dollar', free orders earn 0 points.", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='min_lifetime_points',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum lifetime points earned to qualify.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='loyalty_points_backfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoyaltyPointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('earn', 'Earned'), ('revoke', 'Revoked'), ('adjust', 'Manual adjustment')], db_index=True, max_length=12)),
                ('amount', models.IntegerField(help_text='Signed: + earn, - revoke (applied delta).')),
                ('balance_after', models.PositiveIntegerField()),
                ('lifetime_after', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='tickets.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='tickets.organization')),
                ('ticket_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='tickets.ticketorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='tickets_loy_custome_d217e4_idx'), models.Index(fields=['organization', '-created_at'], name='tickets_loy_organiz_50a99e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ticket_order__isnull', False)), fields=('ticket_order', 'kind'), name='loyaltypoints_one_per_order_kind')],
            },
        ),
    ]
