# Generated by Django 5.2.4 on 2026-06-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0143_eventexpense_api_attributed_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventexpense',
            name='cue_attributed_orders',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventexpense',
            name='cue_attributed_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='attribution',
            field=models.JSONField(blank=True, default=dict, help_text='First-party UTM/fbclid/referrer captured at checkout; copied to the order on fulfillment.'),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='attribution',
            field=models.JSONField(blank=True, default=dict, help_text='First-party UTM/fbclid/referrer captured at checkout for campaign attribution.'),
        ),
    ]
