# Generated by Django 5.2.4 on 2026-06-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0144_customer_lifetime_points_customer_points_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='loyalty_feature_enabled',
            field=models.BooleanField(default=False, help_text='Gates the loyalty program feature (tier builder + points engine) for this org. Off by default; enable per-org for pilot rollout. When off: loyalty pages 404, the sidebar link and customer-detail tier badge are hidden, orders earn no points, and recalc/backfill tasks no-op. Existing data is preserved; revokes of past earns still apply.'),
        ),
    ]
