# Generated by Django 5.2.4 on 2026-06-11 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0143_eventexpense_api_attributed_orders_and_more'),
        ('tickets', '0145_organization_loyalty_feature_enabled'),
    ]

    operations = [
    ]
