# Generated by Django 5.2.4 on 2026-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0147_eventexpense_cue_attributed_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='origin',
            field=models.CharField(choices=[('legacy_transfer', 'Legacy transfer + payout'), ('migration', 'Balance migration (true-up)'), ('cue', 'Requested in Cue'), ('stripe_dashboard', 'Initiated via Stripe')], db_index=True, default='cue', help_text='Which money pool this payout drew from; set explicitly at every creation site.', max_length=20),
        ),
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='charge_flow',
            field=models.CharField(choices=[('platform', 'Platform charge (legacy)'), ('destination', 'Destination charge'), ('direct', 'Direct charge (connected account)')], db_index=True, default='platform', help_text='How the money moved: platform (legacy), destination, or direct (in-person).', max_length=20),
        ),
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, default='', help_text='Transfer (tr_xxx) created by the destination charge; empty for platform/direct flows.', max_length=255),
        ),
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='transfer_cents',
            field=models.PositiveIntegerField(default=0, help_text='Organizer net sent to the connected account by the destination charge.'),
        ),
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='transfer_reversed_cents',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative cents reversed back to the platform after refunds (cache of Stripe state).'),
        ),
    ]
