# Generated by Django 5.2.4 on 2026-06-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0149_backfill_payout_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='feature',
            field=models.CharField(choices=[('chat_agent', 'Chat agent'), ('meta_campaign_match', 'Meta campaign match'), ('mailchimp_campaign_match', 'Mailchimp campaign match'), ('slicktext_campaign_match', 'SlickText campaign match'), ('marketing_narrative', 'Marketing narrative'), ('typeform_event_match', 'Typeform event match'), ('event_summary', 'Event summary')], db_index=True, max_length=50),
        ),
    ]
