# Generated by Django 5.2.4 on 2026-06-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0150_event_ai_summary_event_ai_summary_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ai_event_summary_enabled',
            field=models.BooleanField(default=True, help_text='Show the AI Event Summary card on event detail pages.'),
        ),
    ]
