# Generated by Django 5.2.4 on 2026-06-16 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0151_organization_ai_event_summary_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvformat',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Built-in format maintained by Cue; read-only for organizations.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scanned_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this individual ticket was scanned in (import or live check-in).', null=True),
        ),
        migrations.AlterField(
            model_name='csvformat',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Owning organization, or NULL for a global built-in format.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_formats', to='tickets.organization'),
        ),
    ]
