# Generated by Django 5.2.4 on 2026-06-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0154_backfill_ticket_scanned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsmscampaign',
            name='cue_attributed_orders',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsmscampaign',
            name='cue_attributed_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
