# Generated by Django 5.2.4 on 2026-06-19 02:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


# Composite foreign keys enforcing that a chosen option belongs to the same
# question the answer is for. Postgres-only: SQLite cannot ALTER-ADD a composite
# FK, and dev/tests rely on SurveyAnswerOption.clean() for the same guarantee.
_COMPOSITE_FK_SQL = """
ALTER TABLE tickets_surveyansweroption
    ADD CONSTRAINT surveyansweroption_answer_question_fk
    FOREIGN KEY (answer_id, question_id)
    REFERENCES tickets_surveyanswer (id, question_id)
    DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE tickets_surveyansweroption
    ADD CONSTRAINT surveyansweroption_option_question_fk
    FOREIGN KEY (option_id, question_id)
    REFERENCES tickets_surveyquestionoption (id, question_id)
    DEFERRABLE INITIALLY DEFERRED;
"""

_COMPOSITE_FK_SQL_REVERSE = """
ALTER TABLE tickets_surveyansweroption
    DROP CONSTRAINT IF EXISTS surveyansweroption_answer_question_fk;
ALTER TABLE tickets_surveyansweroption
    DROP CONSTRAINT IF EXISTS surveyansweroption_option_question_fk;
"""


def add_composite_fks(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(_COMPOSITE_FK_SQL)


def drop_composite_fks(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(_COMPOSITE_FK_SQL_REVERSE)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0154_backfill_ticket_scanned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('star_rating', 'Star Rating (1-5)'), ('nps', 'NPS Score (0-10)'), ('text', 'Free Text'), ('single_select', 'Single Choice'), ('multi_select', 'Multiple Choice')], max_length=20),
        ),
        migrations.CreateModel(
            name='SurveyQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tickets.surveyquestion')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswerOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='tickets.surveyanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tickets.surveyquestion')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_options', to='tickets.surveyquestionoption')),
            ],
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, help_text='Chosen option(s) for single_select / multi_select questions', related_name='answers', through='tickets.SurveyAnswerOption', to='tickets.surveyquestionoption'),
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(fields=('id', 'question'), name='surveyanswer_id_question_uniq'),
        ),
        migrations.AddIndex(
            model_name='surveyquestionoption',
            index=models.Index(fields=['question', 'position'], name='tickets_sur_questio_57aa1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyquestionoption',
            constraint=models.UniqueConstraint(fields=('id', 'question'), name='surveyoption_id_question_uniq'),
        ),
        migrations.AddConstraint(
            model_name='surveyansweroption',
            constraint=models.UniqueConstraint(fields=('answer', 'option'), name='surveyansweroption_answer_option_uniq'),
        ),
        migrations.RunPython(add_composite_fks, drop_composite_fks),
    ]
