# Generated by Django 5.2.4 on 2026-06-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0158_posh_map_in_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessagerecipient',
            name='segments',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smsmessagerecipient',
            name='stop_disclosed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='smsmessagerecipient',
            index=models.Index(fields=['phone', 'sent_at'], name='tickets_sms_phone_89ed46_idx'),
        ),
    ]
