# Generated by Django 5.2.4 on 2026-06-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0159_smsmessagerecipient_segments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='survey_email_subject',
            field=models.CharField(blank=True, default='', help_text='Per-event override for the survey email subject. Use {event} for the event name. Blank = org default.', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='survey_email_subject',
            field=models.CharField(blank=True, default='', help_text='Org-wide default subject for survey invitation emails. Use {event} for the event name. Blank = built-in default.', max_length=255),
        ),
    ]
