# Generated by Django 5.2.4 on 2026-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0160_event_survey_email_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinvitation',
            name='scheduled_send_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Absolute UTC time this invitation may be sent. NULL = send immediately. The bulk send task only dispatches rows whose scheduled time is in the past (or NULL).', null=True),
        ),
    ]
