# Generated by Django 5.2.4 on 2026-06-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0161_surveyinvitation_scheduled_send_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='survey_send_offset_type',
            field=models.CharField(blank=True, choices=[('hours', 'hours'), ('days', 'days')], default='', help_text='Per-event override for survey send timing. Blank = org default.', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='survey_send_offset_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='survey_send_time_of_day',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='survey_send_offset_type',
            field=models.CharField(blank=True, choices=[('hours', 'hours'), ('days', 'days')], default='', help_text="Default survey send timing: 'hours' or 'days' after the event ends. Blank = send immediately.", max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='survey_send_offset_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='survey_send_time_of_day',
            field=models.TimeField(blank=True, help_text="Time of day to send when offset_type is 'days' (event timezone).", null=True),
        ),
    ]
