# Generated by Django 5.2.4 on 2026-06-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0162_event_survey_send_offset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='survey_send_anchor',
            field=models.CharField(blank=True, choices=[('end', 'end'), ('start', 'start')], default='', help_text="Per-event override: measure the offset from the event 'start' or 'end'. Blank = end.", max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='survey_send_anchor',
            field=models.CharField(blank=True, choices=[('end', 'end'), ('start', 'start')], default='', help_text="Whether the offset is measured from the event 'start' or 'end'. Blank = end.", max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='survey_send_offset_type',
            field=models.CharField(blank=True, choices=[('hours', 'hours'), ('days', 'days')], default='', help_text="Default survey send timing: 'hours' or 'days' relative to the event. Blank = send immediately.", max_length=10),
        ),
    ]
