# Generated by Django 5.2.4 on 2026-06-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0163_event_survey_send_anchor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='survey_reply_to_email',
            field=models.EmailField(blank=True, default='', help_text='Replies to survey invitations go here, and the org name appears on the From line. Blank = send as Cue with no reply-to.', max_length=254),
        ),
    ]
