# Generated by Django 5.2.4 on 2026-06-26 18:56

from django.db import migrations, models


def enable_for_existing_external_orgs(apps, schema_editor):
    """Backfill: enable the flag for orgs that already use external events / CSV.

    Avoids breaking current users who rely on CSV-imported (external) events.
    An org qualifies if it has any external event or any uploaded CSV file.
    """
    Organization = apps.get_model('tickets', 'Organization')
    Event = apps.get_model('tickets', 'Event')
    UploadedFile = apps.get_model('tickets', 'UploadedFile')

    org_ids = set(
        Event.objects.filter(ticketing_type='external')
        .values_list('organization_id', flat=True)
    )
    org_ids |= set(UploadedFile.objects.values_list('organization_id', flat=True))
    org_ids.discard(None)

    if org_ids:
        Organization.objects.filter(id__in=org_ids).update(external_events_enabled=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0164_organization_survey_reply_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='external_events_enabled',
            field=models.BooleanField(default=False, help_text='Allow this org to create external (CSV-imported) events. Off by default; direct ticketing only.'),
        ),
        migrations.RunPython(enable_for_existing_external_orgs, noop),
    ]
