# Generated by Django 5.2.4 on 2026-06-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0165_organization_external_events_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onboarding_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
