# Generated by Django 5.2.4 on 2026-06-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0166_organization_onboarding_dismissed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='survey_auto_send_opted_out',
            field=models.BooleanField(default=False, help_text="Set when a host cancels a scheduled survey send. Stops the auto-send scheduler from re-arming this event's survey."),
        ),
    ]
