# Generated by Django 5.2.4 on 2026-07-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0167_event_survey_auto_send_opted_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='segment_bands',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='segment_mode',
            field=models.CharField(choices=[('percentile', 'Percentile (relative)'), ('absolute', 'Absolute (fixed cut-offs)')], db_index=True, default='percentile', max_length=12),
        ),
    ]
