# Generated by Django 5.2.4 on 2026-07-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0170_backfill_event_markets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='external_events_enabled',
            field=models.BooleanField(default=True, help_text='Allow this org to create external (CSV-imported) events. On by default (external-first onboarding); a data migration backfilled existing orgs.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sms_marketing_enabled',
            field=models.BooleanField(default=True, help_text='Gates the native marketing SMS feature for this org. On by default for new orgs (existing orgs unchanged by the default flip). Actual sending is still gated by per-customer consent and platform A2P readiness. FeatureFlagSettings is a global singleton and cannot scope to individual orgs, so the SMS gate lives here.'),
        ),
    ]
