# Generated by Django 5.2.4 on 2026-07-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0173_seed_eventbrite_builtin_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='directticketing_upsell_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
