# Generated by Django 5.2.4 on 2026-07-03 23:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0174_organization_directticketing_upsell_dismissed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ai_sms_strategist_enabled',
            field=models.BooleanField(default=True, help_text='Show the AI SMS Campaign Strategist (plan recommendations) entry points.'),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='feature',
            field=models.CharField(choices=[('chat_agent', 'Chat agent'), ('meta_campaign_match', 'Meta campaign match'), ('mailchimp_campaign_match', 'Mailchimp campaign match'), ('slicktext_campaign_match', 'SlickText campaign match'), ('marketing_narrative', 'Marketing narrative'), ('typeform_event_match', 'Typeform event match'), ('event_summary', 'Event summary'), ('sms_plan', 'SMS campaign plan')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='SMSCampaignPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filter_criteria', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=200)),
                ('objective', models.CharField(blank=True, default='', max_length=300)),
                ('strategy_summary', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_campaign_plans', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_campaign_plans', to='tickets.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_campaign_plans', to='tickets.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='tickets_sms_organiz_d21110_idx')],
            },
        ),
    ]
