# Generated by Django 5.2.4 on 2026-07-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0175_organization_ai_sms_strategist_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone (e.g. America/New_York) used when showing scheduled send times. Blank falls back to the site default.', max_length=64),
        ),
    ]
