# Generated by Django 5.2.4 on 2026-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0176_organization_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglink',
            name='target_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
