# Generated by Django 5.2.4 on 2026-07-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0177_trackinglink_target_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ai_summary_input_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='ai_event_summary_auto_regenerate',
            field=models.BooleanField(default=True, help_text="Automatically regenerate an event's AI summary once a day when its underlying data changes after the event ends. When off, summaries are only (re)generated when someone clicks Generate."),
        ),
    ]
