# Generated by Django 5.2.4 on 2026-07-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0178_event_ai_summary_input_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscampaignplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], db_index=True, default='draft', max_length=12),
        ),
    ]
