# Generated by Django 5.2.4 on 2026-07-05 21:42

from django.db import migrations, models


def recompute_status(apps, schema_editor):
    """Derive each plan's status from its steps: In progress once every step has been
    scheduled/launched, else Draft. Also converts any legacy 'ready' rows to a valid value."""
    Plan = apps.get_model('tickets', 'SMSCampaignPlan')
    for plan in Plan.objects.all().iterator():
        steps = plan.steps or []
        all_scheduled = bool(steps) and all(s.get('launched_campaign_id') for s in steps)
        desired = 'in_progress' if all_scheduled else 'draft'
        if plan.status != desired:
            plan.status = desired
            plan.save(update_fields=['status'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0179_smscampaignplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscampaignplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress')], db_index=True, default='draft', max_length=12),
        ),
        migrations.RunPython(recompute_status, noop),
    ]
