# Generated by Django 5.2.4 on 2026-07-06 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0180_alter_smscampaignplan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_text', models.TextField(help_text='The exact disclosure the subscriber agreed to.')),
                ('consent_url', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('subscribe_page', 'Subscribe page'), ('text_join', 'Text to join')], db_index=True, default='subscribe_page', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Set on OTP success; only verified records count as consent.', null=True)),
                ('pending_start', models.BooleanField(default=False, help_text='Phone was globally Twilio-suppressed at consent time; consented but unreachable until they text START. Cleared by the inbound webhook.')),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Linked after the Customer upsert on verification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_consent_records', to='tickets.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_consent_records', to='tickets.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'phone'], name='tickets_sms_organiz_252316_idx'), models.Index(fields=['organization', '-created_at'], name='tickets_sms_organiz_489e1e_idx')],
            },
        ),
    ]
