# Generated by Django 5.2.4 on 2026-07-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0180_alter_smscampaignplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytier',
            name='max_days_since_last_attended',
            field=models.PositiveIntegerField(blank=True, help_text='Must have attended an event within this many days to qualify (attendance recency).', null=True),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='min_events_attended',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum number of distinct events actually attended (checked in) to qualify.', null=True),
        ),
    ]
