# Generated by Django 5.2.4 on 2026-07-08 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0181_smsconsentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='home_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_subscribers', to='tickets.market'),
        ),
    ]
