# Generated by Django 5.2.4 on 2026-07-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0182_customer_home_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sms_subscribe_segment_by_market',
            field=models.BooleanField(default=False, help_text="When on (and the org has >1 market), the public subscribe page asks each new subscriber which market they're in and stores it on Customer.home_market, so market-scoped SMS campaigns can reach them before any purchase."),
        ),
    ]
