# Generated by Django 5.2.4 on 2026-07-10 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0183_loyaltytier_attended_within_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTierTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_at', models.DateTimeField(db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_transitions', to='tickets.customer')),
                ('from_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.loyaltytier')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_transitions', to='tickets.organization')),
                ('to_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.loyaltytier')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['customer', '-changed_at'], name='tickets_loy_custome_4a11c3_idx')],
            },
        ),
    ]
