# Generated by Django 5.2.4 on 2026-07-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0183_organization_sms_subscribe_segment_by_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sms_subscribe_market_label',
            field=models.CharField(blank=True, default='', help_text="Custom label for the market picker on the public subscribe page (e.g. 'Which city?'). Blank falls back to the default 'Your area'.", max_length=60),
        ),
    ]
