# Generated by Django 5.2.4 on 2026-07-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0184_loyaltytiertransition'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytier',
            name='min_paid_orders_recent',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum number of paid orders (total > $0) within the window below to qualify.', null=True),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='paid_orders_within_days',
            field=models.PositiveIntegerField(blank=True, help_text='Only count paid orders placed within this many days. Leave blank to count paid orders over all time.', null=True),
        ),
    ]
