# Generated by Django 5.2.4 on 2026-07-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0186_rename_paid_orders_to_paid_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinvitation',
            name='send_error',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='surveyinvitation',
            name='send_failed_at',
            field=models.DateTimeField(blank=True, help_text='Set when a send permanently fails (invalid/refused recipient). Excludes the row from future send attempts.', null=True),
        ),
    ]
