# Generated by Django 5.2.4 on 2026-07-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0184_organization_sms_subscribe_market_label'),
        ('tickets', '0187_surveyinvitation_send_error_and_more'),
    ]

    operations = [
    ]
