# Generated by Django 5.2.4 on 2026-07-17 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0188_merge_20260716_2146'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='customer_org_email_unique',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'phone'], name='tickets_cus_organiz_c54dbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('organization', 'email'), name='customer_org_email_unique'),
        ),
    ]
