# Generated by Codex on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0189_remove_customer_customer_org_email_unique_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(
                fields=('organization', 'phone'),
                condition=models.Q(email='') & ~models.Q(phone=''),
                name='customer_org_phone_phone_only_unique',
            ),
        ),
    ]
