# Generated by Django 5.2.4 on 2026-07-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0190_customer_phone_only_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sms_subscribe_title',
            field=models.CharField(blank=True, default='', help_text="Optional header shown above the mobile number field on the public subscribe page (e.g. 'Join the Tempo Global text list'). Blank shows no header (the org name still appears as the page heading).", max_length=80),
        ),
    ]
