# Generated by Django 5.2.4 on 2026-07-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0191_organization_sms_subscribe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='customer_list_columns',
            field=models.JSONField(blank=True, default=None, help_text='Visible optional columns on the Customers table (list of keys). Null = show all default columns.', null=True),
        ),
    ]
