# Generated by Django 5.2.4 on 2026-07-18 14:46

import django.db.models.deletion
import tickets.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0191_organization_sms_subscribe_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Label to identify this endpoint, e.g. 'Zapier — new orders'", max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(default=tickets.models._generate_webhook_secret, help_text='Used to HMAC-sign each delivery. Verify with the X-Cue-Signature header.', max_length=100)),
                ('event_types', models.JSONField(blank=True, default=list, help_text="List of subscribed event-type strings, e.g. ['event.created', 'order.created'].")),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='tickets.organization')),
            ],
            options={
                'verbose_name': 'Webhook endpoint',
                'verbose_name_plural': 'Webhook endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('error_message', models.CharField(blank=True, default='', max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='tickets.organization')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='tickets.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook delivery',
                'verbose_name_plural': 'Webhook deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['organization', 'is_active'], name='tickets_web_organiz_55577c_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', 'created_at'], name='tickets_web_endpoin_7490a0_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['organization', 'event_type', 'created_at'], name='tickets_web_organiz_4708c7_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['success', 'created_at'], name='tickets_web_success_cc3bf5_idx'),
        ),
    ]
