# Generated by Django 5.2.4 on 2026-07-18 15:54

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0192_webhookendpoint_webhookdelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='delivery_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='secret',
            field=models.CharField(default=tickets.models._generate_webhook_secret, help_text='Used to HMAC-sign each delivery. Verify with the X-Cue-Signature header. Deliveries sign with the CURRENT secret at send time, so rotating it can cause in-flight/retrying deliveries to fail verification with the old secret.', max_length=100),
        ),
    ]
