# Generated by Django 5.2.4 on 2026-07-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0193_organization_customer_list_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='acquisition_source',
            field=models.CharField(blank=True, choices=[('subscribe_form', 'Opt-in form'), ('ticket_purchase', 'Ticket purchase'), ('import', 'CSV Import'), ('manual', 'Manual')], db_index=True, help_text='How this customer first entered the org. Set once at creation; immutable.', max_length=20),
        ),
    ]
