# Generated by Django 5.2.4 on 2026-07-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0195_webhookendpoint_webhookdelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='instagram_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='tiktok_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='youtube_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
