# Generated by Django 5.2.4 on 2026-07-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0196_organization_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscampaignplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], db_index=True, default='draft', max_length=12),
        ),
    ]
