# Generated by Django 5.2.4 on 2026-07-23 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0199_backfill_launched_plan_step_bodies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tap_to_pay_enabled_push_sent',
            field=models.BooleanField(default=False, help_text="True once the one-time 'Tap to Pay is ready' push has been sent to this org's devices. Guards against duplicate sends across the many account.updated webhooks Stripe fires."),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=200, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS')], default='ios', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='tickets.organization')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='tickets_dev_organiz_e1b4c9_idx')],
            },
        ),
    ]
