# Generated by Django 5.2.4 on 2026-07-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0199_backfill_launched_plan_step_bodies'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscampaign',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
