# Generated by Django 5.2.4 on 2026-07-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0200_organization_tap_to_pay_enabled_push_sent_and_more'),
        ('tickets', '0200_smscampaign_failure_reason'),
    ]

    operations = [
    ]
