# Generated by Django 5.2.4 on 2026-08-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0203_alter_aitokenusage_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='disabled_action_kinds',
            field=models.JSONField(blank=True, default=list, help_text='List of AIRecommendation.Kind values this org has turned off in the Action Center. Disabled kinds are hidden at read time everywhere (the Action Center page, per-event badges on the events list, and the sidebar count); they keep being generated, so re-enabling a kind restores its suggestions immediately. Empty list = all kinds enabled.'),
        ),
    ]
