# Generated by Django 5.2.4 on 2026-08-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0204_organization_disabled_action_kinds'),
        ('tickets', '0204_smscampaign_attribution'),
    ]

    operations = [
    ]
