# Generated by Django 5.2.4 on 2026-08-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0205_merge_20260802_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscampaign',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='tickets.smscampaignplan'),
        ),
        migrations.AddField(
            model_name='smscampaignplan',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
