# Generated by Django 5.2.4 on 2026-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0206_smscampaign_plan_smscampaignplan_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
