# Generated by Django 5.2.4 on 2026-08-12 15:46

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0207_userprofile_instagram_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=tickets.models._get_media_storage, upload_to='user_avatars/'),
        ),
    ]
