# Generated by Django 5.2.4 on 2026-08-14 00:51

import django.db.models.deletion
import tickets.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0208_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=tickets.models._get_media_storage, upload_to=tickets.models._event_image_upload_to)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tickets.event')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
