# Generated by Django 5.2.4 on 2026-08-21 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0209_eventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessagingService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='Human-readable name, e.g. "Toll-Free" or "A2P 10DLC".', max_length=100)),
                ('messaging_service_sid', models.CharField(help_text='Twilio Messaging Service SID (starts with "MG").', max_length=64)),
                ('sms_from', models.CharField(blank=True, help_text='Optional fallback sender number (E.164) used when no Messaging Service SID is set on this row.', max_length=20)),
                ('daily_segment_cap', models.PositiveIntegerField(default=2000, help_text='Daily segment ceiling for this service (e.g. 10000 toll-free, 2000 A2P). 0 disables the daily-cap guard.')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Only one service is active at a time; the active one is used for all marketing sends.')),
            ],
            options={
                'verbose_name': 'SMS Messaging Service',
                'verbose_name_plural': 'SMS Messaging Services',
                'ordering': ['-is_active', 'label'],
            },
        ),
    ]
