# Generated by Django 5.2.4 on 2026-08-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0211_seed_sms_messaging_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessagerecipient',
            name='refunded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
