# Generated by Django 5.2.4 on 2026-10-05 23:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0212_smsmessagerecipient_refunded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ig_user_id', models.CharField(db_index=True, max_length=64)),
                ('ig_username', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_human', 'Awaiting human'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('author', models.CharField(choices=[('customer', 'Customer'), ('agent', 'AI agent'), ('human', 'Human')], max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('received', 'Received'), ('auto_sent', 'Auto-sent'), ('pending_review', 'Pending review'), ('approved_sent', 'Approved & sent'), ('failed', 'Failed'), ('discarded', 'Discarded')], default='received', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('escalation_category', models.CharField(blank=True, default='', max_length=40)),
                ('escalation_reason', models.CharField(blank=True, default='', max_length=300)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('token_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgFAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('topic', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_business_account_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_page_access_token',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_page_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_support_agent_enabled',
            field=models.BooleanField(default=False, help_text='When on, the Instagram DM support agent auto-answers routine FAQ DMs and queues the rest for review.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_username',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='feature',
            field=models.CharField(choices=[('chat_agent', 'Chat agent'), ('meta_campaign_match', 'Meta campaign match'), ('mailchimp_campaign_match', 'Mailchimp campaign match'), ('slicktext_campaign_match', 'SlickText campaign match'), ('marketing_narrative', 'Marketing narrative'), ('typeform_event_match', 'Typeform event match'), ('event_summary', 'Event summary'), ('sms_plan', 'SMS campaign plan'), ('brand_voice_example', 'Brand voice example'), ('ig_support_agent', 'Instagram support agent')], db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('instagram_business_account_id', ''), _negated=True), fields=('instagram_business_account_id',), name='org_ig_business_acct_unique'),
        ),
        migrations.AddField(
            model_name='instagramconversation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ig_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instagramconversation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ig_conversations', to='tickets.customer'),
        ),
        migrations.AddField(
            model_name='instagramconversation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_conversations', to='tickets.organization'),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.instagramconversation'),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_messages', to='tickets.organization'),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ig_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgfaq',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgfaq',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='tickets.organization'),
        ),
        migrations.AddField(
            model_name='orgfaq',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='instagramconversation',
            index=models.Index(fields=['organization', 'status', 'last_message_at'], name='ig_conv_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='instagramconversation',
            constraint=models.UniqueConstraint(fields=('organization', 'ig_user_id'), name='ig_conv_org_user_unique'),
        ),
        migrations.AddIndex(
            model_name='instagrammessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ig_msg_conv_time_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrammessage',
            index=models.Index(fields=['provider_message_id'], name='ig_msg_provider_idx'),
        ),
        migrations.AddConstraint(
            model_name='instagrammessage',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id', ''), _negated=True), fields=('organization', 'provider_message_id'), name='ig_msg_provider_unique'),
        ),
        migrations.AddIndex(
            model_name='orgfaq',
            index=models.Index(fields=['organization', 'is_published'], name='orgfaq_org_pub_idx'),
        ),
    ]
