# Generated by Django 5.2.4 on 2026-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0213_instagramconversation_instagrammessage_orgfaq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='show_page_views_for_external_events',
            field=models.BooleanField(default=False, help_text='Show the Page Views column for CSV (external) events and allow organizers to enter the value manually. Direct events always show their tracked page views.'),
        ),
    ]
