# Generated by Django 5.2.4 on 2026-10-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0214_organization_show_page_views_for_external_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='instagram_escalation_ack_text',
            field=models.TextField(blank=True, default='Thanks for your message! A team member will follow up with you shortly.', help_text="Auto-sent to the customer the moment a DM is escalated to a human, so an escalated thread isn't met with silence while it waits for a reply. Leave blank to send no acknowledgement."),
        ),
        migrations.AlterField(
            model_name='instagrammessage',
            name='author',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'AI agent'), ('human', 'Human'), ('system', 'Automated')], max_length=10),
        ),
    ]
