# Generated by Django 5.2.4 on 2026-10-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0215_organization_instagram_escalation_ack_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='instagram_feature_enabled',
            field=models.BooleanField(default=False, help_text='Master visibility gate for the Instagram DM agent UX (inbox, FAQ editor, settings, integration card). Off by default so the feature can ship dark and be turned on per org. Distinct from instagram_support_agent_enabled, which controls whether the agent actually auto-answers at runtime.'),
        ),
    ]
