# Generated by Django 5.2.4 on 2026-10-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0216_organization_instagram_feature_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramconversation',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('awaiting_human', 'Awaiting human'), ('human_handling', 'With human'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
