# Generated by Django 5.2.4 on 2026-10-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0217_alter_instagramconversation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconversation',
            name='agent_context_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
