# Generated by Django 5.2.4 on 2026-10-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0218_instagramconversation_agent_context_reset_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='instagram_escalation_ack_text',
        ),
    ]
