# Generated by Django 5.2.4 on 2026-10-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0219_remove_organization_instagram_escalation_ack_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='competition_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='competition_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='competition_input_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='competition_label',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='competition_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='competition_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='market_competition_enabled',
            field=models.BooleanField(default=False, help_text='Enable the per-event Market Competition scan (ships dark; turn on per org).'),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='feature',
            field=models.CharField(choices=[('chat_agent', 'Chat agent'), ('meta_campaign_match', 'Meta campaign match'), ('mailchimp_campaign_match', 'Mailchimp campaign match'), ('slicktext_campaign_match', 'SlickText campaign match'), ('marketing_narrative', 'Marketing narrative'), ('typeform_event_match', 'Typeform event match'), ('event_summary', 'Event summary'), ('sms_plan', 'SMS campaign plan'), ('brand_voice_example', 'Brand voice example'), ('ig_support_agent', 'Instagram support agent'), ('market_competition', 'Market competition')], db_index=True, max_length=50),
        ),
    ]
